### ISSUE TITLE
This relative module was not found: issue when fresh install

### ISSUE THREAD

**Issue by vikramIde** [AppointmentGuru/webpack-mobile-f7#2]
Hello Guys,

So I did a fresh install and everything worked fine untill i rad 
```npm run dev``` I am getting following error

```
This relative module was not found:

* ./components/pages/about.vue in ./src/routes.js
> Listening at http://localhost:8080
```

I check the folder and about.vue is existing,  is it some kind of permission issue ?

**Comment by vikramIde** [comment]
Fixed 

the name of the file should be in Caps

**Comment by toast38coza** [comment]
Thanks for the fix. You pull request has been merged
